# -*- python -*-
# This file contains rules for Bazel;
cc_binary(
    name = "hello-dudes",
    srcs = [
        "hello.cpp",
    ],
    deps = [
        "@drake//drake/automotive:curve2",
        "//shambhala:hello",
    ],
)
