# -*- python -*-

# This file marks a workspace root for the Bazel build system. see
# http://bazel.io/ .

# To temporarily use a local copy of a github_archive, within this file add a
# local_repository_archive argument to its github_archive macro call, e.g.:
#
# github_archive(
#     name = "foobar",
#     local_repository_override = "/path/to/local/foo/bar",
#     repository = "foo/bar",
#     commit = "0123456789abcdef0123456789abcdef01234567",
#     sha256 = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
# )

workspace(name = "bazel_drake_sources")

##############################################################################
# The Drakeverse
##############################################################################

local_repository(
    name = "drake",
    path = "externals/drake-distro",
)

# Use workaround from:
# * https://github.com/bazelbuild/bazel/issues/2757#issuecomment-290448615
# * https://groups.google.com/forum/#!topic/bazel-discuss/OhBIZ1DzSIw

# Copied from @drake//WORKSPACE. Ensure that this is syncrhonized!!!
# -- START Required Load-Level Transitive Dependencies
load("@drake//tools:github.bzl", "github_archive")
# Required for buildifier.
github_archive(
    name = "io_bazel_rules_go",
    repository = "bazelbuild/rules_go",
    commit = "0.4.4",
    sha256 = "afec53d875013de6cebe0e51943345c587b41263fdff36df5ff651fbf03c1c08",
)
# -- END Required Load-Level Transitive Dependencies

load("@drake//tools:drake_deps.bzl", "drake_deps")
drake_deps() # Ignore install_dir, don't need drake-visualizer right now
